__version__ = "0.3.0"

from . import svg, tags
from ._core import TagAttrArg  # pyright: ignore[reportUnusedImport]  # noqa: F401
from ._core import TagChildArg  # pyright: ignore[reportUnusedImport]  # noqa: F401
from ._core import (
    HTML,
    HTMLDependency,
    HTMLDocument,
    MetadataNode,
    RenderedHTML,
    Tag,
    TagAttrs,
    TagAttrValue,
    TagChild,
    TagFunction,
    Tagifiable,
    TagList,
    TagNode,
    head_content,
)
from ._util import css, html_escape
from .tags import (
    a,
    br,
    code,
    div,
    em,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    hr,
    img,
    p,
    pre,
    span,
    strong,
)

__all__ = (
    "svg",
    "tags",
    "HTML",
    "HTMLDependency",
    "HTMLDocument",
    "MetadataNode",
    "RenderedHTML",
    "Tag",
    "TagAttrs",
    "TagAttrValue",
    "TagChild",
    "TagFunction",
    "Tagifiable",
    "TagList",
    "TagNode",
    "head_content",
    "css",
    "html_escape",
    "a",
    "br",
    "code",
    "div",
    "em",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "img",
    "p",
    "pre",
    "span",
    "strong",
)
