# Do not edit by hand; this file is generated by ./scripts/generate_tags.py
# fmt: off

"""
Functions for creating SVG tags.
"""

from typing import Optional, List

from ._core import Tag, TagChildArg, TagAttrArg


def a(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <a> tag.

    Creates the <a> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("a", *args, children=children, **kwargs)


def animate(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <animate> tag.

    Creates the <animate> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("animate", *args, children=children, **kwargs)


def animateMotion(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <animateMotion> tag.

    Creates the <animateMotion> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("animateMotion", *args, children=children, **kwargs)


def animateTransform(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <animateTransform> tag.

    Creates the <animateTransform> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("animateTransform", *args, children=children, **kwargs)


def circle(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <circle> tag.

    Creates the <circle> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("circle", *args, children=children, **kwargs)


def clipPath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <clipPath> tag.

    Creates the <clipPath> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("clipPath", *args, children=children, **kwargs)


def defs(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <defs> tag.

    Creates the <defs> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("defs", *args, children=children, **kwargs)


def desc(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <desc> tag.

    Creates the <desc> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("desc", *args, children=children, **kwargs)


def discard(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <discard> tag.

    Creates the <discard> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/discard

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("discard", *args, children=children, **kwargs)


def ellipse(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <ellipse> tag.

    Creates the <ellipse> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("ellipse", *args, children=children, **kwargs)


def feBlend(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feBlend> tag.

    Creates the <feBlend> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feBlend

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feBlend", *args, children=children, **kwargs)


def feColorMatrix(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feColorMatrix> tag.

    Creates the <feColorMatrix> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feColorMatrix

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feColorMatrix", *args, children=children, **kwargs)


def feComponentTransfer(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feComponentTransfer> tag.

    Creates the <feComponentTransfer> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComponentTransfer

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feComponentTransfer", *args, children=children, **kwargs)


def feComposite(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feComposite> tag.

    Creates the <feComposite> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feComposite", *args, children=children, **kwargs)


def feConvolveMatrix(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feConvolveMatrix> tag.

    Creates the <feConvolveMatrix> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feConvolveMatrix

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feConvolveMatrix", *args, children=children, **kwargs)


def feDiffuseLighting(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feDiffuseLighting> tag.

    Creates the <feDiffuseLighting> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDiffuseLighting

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feDiffuseLighting", *args, children=children, **kwargs)


def feDisplacementMap(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feDisplacementMap> tag.

    Creates the <feDisplacementMap> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDisplacementMap

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feDisplacementMap", *args, children=children, **kwargs)


def feDistantLight(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feDistantLight> tag.

    Creates the <feDistantLight> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDistantLight

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feDistantLight", *args, children=children, **kwargs)


def feDropShadow(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feDropShadow> tag.

    Creates the <feDropShadow> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feDropShadow", *args, children=children, **kwargs)


def feFlood(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feFlood> tag.

    Creates the <feFlood> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFlood

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feFlood", *args, children=children, **kwargs)


def feFuncA(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feFuncA> tag.

    Creates the <feFuncA> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncA

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feFuncA", *args, children=children, **kwargs)


def feFuncB(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feFuncB> tag.

    Creates the <feFuncB> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncB

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feFuncB", *args, children=children, **kwargs)


def feFuncG(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feFuncG> tag.

    Creates the <feFuncG> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncG

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feFuncG", *args, children=children, **kwargs)


def feFuncR(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feFuncR> tag.

    Creates the <feFuncR> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncR

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feFuncR", *args, children=children, **kwargs)


def feGaussianBlur(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feGaussianBlur> tag.

    Creates the <feGaussianBlur> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feGaussianBlur", *args, children=children, **kwargs)


def feImage(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feImage> tag.

    Creates the <feImage> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feImage

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feImage", *args, children=children, **kwargs)


def feMerge(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feMerge> tag.

    Creates the <feMerge> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMerge

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feMerge", *args, children=children, **kwargs)


def feMergeNode(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feMergeNode> tag.

    Creates the <feMergeNode> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMergeNode

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feMergeNode", *args, children=children, **kwargs)


def feMorphology(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feMorphology> tag.

    Creates the <feMorphology> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMorphology

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feMorphology", *args, children=children, **kwargs)


def feOffset(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feOffset> tag.

    Creates the <feOffset> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feOffset

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feOffset", *args, children=children, **kwargs)


def fePointLight(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <fePointLight> tag.

    Creates the <fePointLight> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("fePointLight", *args, children=children, **kwargs)


def feSpecularLighting(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feSpecularLighting> tag.

    Creates the <feSpecularLighting> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpecularLighting

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feSpecularLighting", *args, children=children, **kwargs)


def feSpotLight(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feSpotLight> tag.

    Creates the <feSpotLight> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feSpotLight", *args, children=children, **kwargs)


def feTile(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feTile> tag.

    Creates the <feTile> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTile

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feTile", *args, children=children, **kwargs)


def feTurbulence(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <feTurbulence> tag.

    Creates the <feTurbulence> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTurbulence

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("feTurbulence", *args, children=children, **kwargs)


def filter(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <filter> tag.

    Creates the <filter> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("filter", *args, children=children, **kwargs)


def foreignObject(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <foreignObject> tag.

    Creates the <foreignObject> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("foreignObject", *args, children=children, **kwargs)


def g(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <g> tag.

    Creates the <g> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("g", *args, children=children, **kwargs)


def hatch(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <hatch> tag.

    Creates the <hatch> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatch

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("hatch", *args, children=children, **kwargs)


def hatchpath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <hatchpath> tag.

    Creates the <hatchpath> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatchpath

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("hatchpath", *args, children=children, **kwargs)


def image(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <image> tag.

    Creates the <image> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("image", *args, children=children, **kwargs)


def line(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <line> tag.

    Creates the <line> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("line", *args, children=children, **kwargs)


def linearGradient(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <linearGradient> tag.

    Creates the <linearGradient> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("linearGradient", *args, children=children, **kwargs)


def marker(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <marker> tag.

    Creates the <marker> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("marker", *args, children=children, **kwargs)


def mask(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <mask> tag.

    Creates the <mask> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("mask", *args, children=children, **kwargs)


def metadata(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <metadata> tag.

    Creates the <metadata> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("metadata", *args, children=children, **kwargs)


def mpath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <mpath> tag.

    Creates the <mpath> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mpath

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("mpath", *args, children=children, **kwargs)


def path(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <path> tag.

    Creates the <path> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("path", *args, children=children, **kwargs)


def pattern(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <pattern> tag.

    Creates the <pattern> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("pattern", *args, children=children, **kwargs)


def polygon(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <polygon> tag.

    Creates the <polygon> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("polygon", *args, children=children, **kwargs)


def polyline(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <polyline> tag.

    Creates the <polyline> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("polyline", *args, children=children, **kwargs)


def radialGradient(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <radialGradient> tag.

    Creates the <radialGradient> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("radialGradient", *args, children=children, **kwargs)


def rect(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <rect> tag.

    Creates the <rect> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("rect", *args, children=children, **kwargs)


def script(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <script> tag.

    Creates the <script> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("script", *args, children=children, **kwargs)


def set(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <set> tag.

    Creates the <set> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/set

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("set", *args, children=children, **kwargs)


def stop(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <stop> tag.

    Creates the <stop> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("stop", *args, children=children, **kwargs)


def style(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <style> tag.

    Creates the <style> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("style", *args, children=children, **kwargs)


def svg(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <svg> tag.

    Creates the <svg> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("svg", *args, children=children, **kwargs)


def switch(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <switch> tag.

    Creates the <switch> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("switch", *args, children=children, **kwargs)


def symbol(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <symbol> tag.

    Creates the <symbol> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("symbol", *args, children=children, **kwargs)


def text(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <text> tag.

    Creates the <text> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("text", *args, children=children, **kwargs)


def textPath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <textPath> tag.

    Creates the <textPath> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("textPath", *args, children=children, **kwargs)


def title(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <title> tag.

    Creates the <title> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("title", *args, children=children, **kwargs)


def tspan(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <tspan> tag.

    Creates the <tspan> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("tspan", *args, children=children, **kwargs)


def use(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <use> tag.

    Creates the <use> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("use", *args, children=children, **kwargs)


def view(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    """
    Create a <view> tag.

    Creates the <view> SVG element. Learn more at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view

    Parameters
    ----------
    *args
        Child elements to this tag.
    children
        Child elements to this tag.
    **kwargs
        Attributes to this tag.

    Returns
    -------
    Tag
    """

    return Tag("view", *args, children=children, **kwargs)


