# Do not edit by hand; this file is generated by ./scripts/generate_tags.py
# fmt: off

from typing import Optional, List

from .core import tag, TagChild, AttrType

def a(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('a', *args, children=children, **kwargs)

def abbr(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('abbr', *args, children=children, **kwargs)

def acronym(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('acronym', *args, children=children, **kwargs)

def address(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('address', *args, children=children, **kwargs)

def animate(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('animate', *args, children=children, **kwargs)

def animateMotion(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('animateMotion', *args, children=children, **kwargs)

def animateTransform(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('animateTransform', *args, children=children, **kwargs)

def applet(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('applet', *args, children=children, **kwargs)

def area(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('area', *args, children=children, **kwargs)

def article(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('article', *args, children=children, **kwargs)

def aside(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('aside', *args, children=children, **kwargs)

def audio(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('audio', *args, children=children, **kwargs)

def b(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('b', *args, children=children, **kwargs)

def base(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('base', *args, children=children, **kwargs)

def basefont(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('basefont', *args, children=children, **kwargs)

def bdi(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('bdi', *args, children=children, **kwargs)

def bdo(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('bdo', *args, children=children, **kwargs)

def bgsound(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('bgsound', *args, children=children, **kwargs)

def big(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('big', *args, children=children, **kwargs)

def blink(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('blink', *args, children=children, **kwargs)

def blockquote(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('blockquote', *args, children=children, **kwargs)

def body(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('body', *args, children=children, **kwargs)

def br(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('br', *args, children=children, **kwargs)

def button(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('button', *args, children=children, **kwargs)

def canvas(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('canvas', *args, children=children, **kwargs)

def caption(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('caption', *args, children=children, **kwargs)

def center(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('center', *args, children=children, **kwargs)

def circle(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('circle', *args, children=children, **kwargs)

def cite(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('cite', *args, children=children, **kwargs)

def clipPath(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('clipPath', *args, children=children, **kwargs)

def code(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('code', *args, children=children, **kwargs)

def col(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('col', *args, children=children, **kwargs)

def colgroup(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('colgroup', *args, children=children, **kwargs)

def command(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('command', *args, children=children, **kwargs)

def content(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('content', *args, children=children, **kwargs)

def data(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('data', *args, children=children, **kwargs)

def datalist(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('datalist', *args, children=children, **kwargs)

def dd(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('dd', *args, children=children, **kwargs)

def defs(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('defs', *args, children=children, **kwargs)

def desc(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('desc', *args, children=children, **kwargs)

def details(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('details', *args, children=children, **kwargs)

def dfn(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('dfn', *args, children=children, **kwargs)

def dialog(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('dialog', *args, children=children, **kwargs)

def dir(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('dir', *args, children=children, **kwargs)

def discard(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('discard', *args, children=children, **kwargs)

def div(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('div', *args, children=children, **kwargs)

def dl(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('dl', *args, children=children, **kwargs)

def dt(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('dt', *args, children=children, **kwargs)

def ellipse(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('ellipse', *args, children=children, **kwargs)

def em(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('em', *args, children=children, **kwargs)

def embed(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('embed', *args, children=children, **kwargs)

def eventsource(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('eventsource', *args, children=children, **kwargs)

def feBlend(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feBlend', *args, children=children, **kwargs)

def feColorMatrix(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feColorMatrix', *args, children=children, **kwargs)

def feComponentTransfer(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feComponentTransfer', *args, children=children, **kwargs)

def feComposite(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feComposite', *args, children=children, **kwargs)

def feConvolveMatrix(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feConvolveMatrix', *args, children=children, **kwargs)

def feDiffuseLighting(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feDiffuseLighting', *args, children=children, **kwargs)

def feDisplacementMap(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feDisplacementMap', *args, children=children, **kwargs)

def feDistantLight(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feDistantLight', *args, children=children, **kwargs)

def feDropShadow(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feDropShadow', *args, children=children, **kwargs)

def feFlood(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feFlood', *args, children=children, **kwargs)

def feFuncA(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feFuncA', *args, children=children, **kwargs)

def feFuncB(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feFuncB', *args, children=children, **kwargs)

def feFuncG(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feFuncG', *args, children=children, **kwargs)

def feFuncR(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feFuncR', *args, children=children, **kwargs)

def feGaussianBlur(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feGaussianBlur', *args, children=children, **kwargs)

def feImage(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feImage', *args, children=children, **kwargs)

def feMerge(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feMerge', *args, children=children, **kwargs)

def feMergeNode(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feMergeNode', *args, children=children, **kwargs)

def feMorphology(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feMorphology', *args, children=children, **kwargs)

def feOffset(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feOffset', *args, children=children, **kwargs)

def fePointLight(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('fePointLight', *args, children=children, **kwargs)

def feSpecularLighting(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feSpecularLighting', *args, children=children, **kwargs)

def feSpotLight(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feSpotLight', *args, children=children, **kwargs)

def feTile(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feTile', *args, children=children, **kwargs)

def feTurbulence(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('feTurbulence', *args, children=children, **kwargs)

def fieldset(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('fieldset', *args, children=children, **kwargs)

def figcaption(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('figcaption', *args, children=children, **kwargs)

def figure(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('figure', *args, children=children, **kwargs)

def filter(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('filter', *args, children=children, **kwargs)

def font(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('font', *args, children=children, **kwargs)

def footer(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('footer', *args, children=children, **kwargs)

def foreignObject(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('foreignObject', *args, children=children, **kwargs)

def form(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('form', *args, children=children, **kwargs)

def frame(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('frame', *args, children=children, **kwargs)

def frameset(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('frameset', *args, children=children, **kwargs)

def g(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('g', *args, children=children, **kwargs)

def h1(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('h1', *args, children=children, **kwargs)

def h2(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('h2', *args, children=children, **kwargs)

def h3(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('h3', *args, children=children, **kwargs)

def h4(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('h4', *args, children=children, **kwargs)

def h5(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('h5', *args, children=children, **kwargs)

def h6(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('h6', *args, children=children, **kwargs)

def hatch(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('hatch', *args, children=children, **kwargs)

def hatchpath(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('hatchpath', *args, children=children, **kwargs)

def header(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('header', *args, children=children, **kwargs)

def hgroup(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('hgroup', *args, children=children, **kwargs)

def hr(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('hr', *args, children=children, **kwargs)

def html(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('html', *args, children=children, **kwargs)

def i(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('i', *args, children=children, **kwargs)

def iframe(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('iframe', *args, children=children, **kwargs)

def image(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('image', *args, children=children, **kwargs)

def img(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('img', *args, children=children, **kwargs)

def input(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('input', *args, children=children, **kwargs)

def ins(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('ins', *args, children=children, **kwargs)

def kbd(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('kbd', *args, children=children, **kwargs)

def keygen(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('keygen', *args, children=children, **kwargs)

def label(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('label', *args, children=children, **kwargs)

def legend(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('legend', *args, children=children, **kwargs)

def li(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('li', *args, children=children, **kwargs)

def line(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('line', *args, children=children, **kwargs)

def linearGradient(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('linearGradient', *args, children=children, **kwargs)

def link(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('link', *args, children=children, **kwargs)

def main(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('main', *args, children=children, **kwargs)

def map(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('map', *args, children=children, **kwargs)

def mark(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('mark', *args, children=children, **kwargs)

def marker(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('marker', *args, children=children, **kwargs)

def marquee(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('marquee', *args, children=children, **kwargs)

def mask(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('mask', *args, children=children, **kwargs)

def menu(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('menu', *args, children=children, **kwargs)

def menuitem(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('menuitem', *args, children=children, **kwargs)

def mesh(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('mesh', *args, children=children, **kwargs)

def meshgradient(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('meshgradient', *args, children=children, **kwargs)

def meshpatch(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('meshpatch', *args, children=children, **kwargs)

def meshrow(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('meshrow', *args, children=children, **kwargs)

def meta(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('meta', *args, children=children, **kwargs)

def metadata(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('metadata', *args, children=children, **kwargs)

def meter(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('meter', *args, children=children, **kwargs)

def mpath(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('mpath', *args, children=children, **kwargs)

def nav(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('nav', *args, children=children, **kwargs)

def nobr(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('nobr', *args, children=children, **kwargs)

def noembed(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('noembed', *args, children=children, **kwargs)

def noframes(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('noframes', *args, children=children, **kwargs)

def noscript(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('noscript', *args, children=children, **kwargs)

def object(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('object', *args, children=children, **kwargs)

def ol(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('ol', *args, children=children, **kwargs)

def optgroup(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('optgroup', *args, children=children, **kwargs)

def option(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('option', *args, children=children, **kwargs)

def output(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('output', *args, children=children, **kwargs)

def p(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('p', *args, children=children, **kwargs)

def param(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('param', *args, children=children, **kwargs)

def path(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('path', *args, children=children, **kwargs)

def pattern(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('pattern', *args, children=children, **kwargs)

def picture(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('picture', *args, children=children, **kwargs)

def plaintext(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('plaintext', *args, children=children, **kwargs)

def polygon(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('polygon', *args, children=children, **kwargs)

def polyline(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('polyline', *args, children=children, **kwargs)

def portal(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('portal', *args, children=children, **kwargs)

def pre(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('pre', *args, children=children, **kwargs)

def progress(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('progress', *args, children=children, **kwargs)

def q(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('q', *args, children=children, **kwargs)

def radialGradient(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('radialGradient', *args, children=children, **kwargs)

def rb(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('rb', *args, children=children, **kwargs)

def rect(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('rect', *args, children=children, **kwargs)

def rp(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('rp', *args, children=children, **kwargs)

def rt(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('rt', *args, children=children, **kwargs)

def rtc(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('rtc', *args, children=children, **kwargs)

def ruby(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('ruby', *args, children=children, **kwargs)

def s(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('s', *args, children=children, **kwargs)

def samp(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('samp', *args, children=children, **kwargs)

def script(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('script', *args, children=children, **kwargs)

def section(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('section', *args, children=children, **kwargs)

def select(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('select', *args, children=children, **kwargs)

def set(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('set', *args, children=children, **kwargs)

def shadow(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('shadow', *args, children=children, **kwargs)

def slot(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('slot', *args, children=children, **kwargs)

def small(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('small', *args, children=children, **kwargs)

def solidcolor(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('solidcolor', *args, children=children, **kwargs)

def source(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('source', *args, children=children, **kwargs)

def spacer(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('spacer', *args, children=children, **kwargs)

def span(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('span', *args, children=children, **kwargs)

def stop(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('stop', *args, children=children, **kwargs)

def strike(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('strike', *args, children=children, **kwargs)

def strong(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('strong', *args, children=children, **kwargs)

def style(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('style', *args, children=children, **kwargs)

def sub(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('sub', *args, children=children, **kwargs)

def summary(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('summary', *args, children=children, **kwargs)

def sup(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('sup', *args, children=children, **kwargs)

def svg(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('svg', *args, children=children, **kwargs)

def switch(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('switch', *args, children=children, **kwargs)

def symbol(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('symbol', *args, children=children, **kwargs)

def table(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('table', *args, children=children, **kwargs)

def tbody(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('tbody', *args, children=children, **kwargs)

def td(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('td', *args, children=children, **kwargs)

def template(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('template', *args, children=children, **kwargs)

def text(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('text', *args, children=children, **kwargs)

def textarea(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('textarea', *args, children=children, **kwargs)

def textPath(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('textPath', *args, children=children, **kwargs)

def tfoot(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('tfoot', *args, children=children, **kwargs)

def th(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('th', *args, children=children, **kwargs)

def thead(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('thead', *args, children=children, **kwargs)

def time(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('time', *args, children=children, **kwargs)

def title(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('title', *args, children=children, **kwargs)

def tr(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('tr', *args, children=children, **kwargs)

def track(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('track', *args, children=children, **kwargs)

def tspan(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('tspan', *args, children=children, **kwargs)

def tt(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('tt', *args, children=children, **kwargs)

def u(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('u', *args, children=children, **kwargs)

def ul(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('ul', *args, children=children, **kwargs)

def unknown(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('unknown', *args, children=children, **kwargs)

def use(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('use', *args, children=children, **kwargs)

def var(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('var', *args, children=children, **kwargs)

def video(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('video', *args, children=children, **kwargs)

def view(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('view', *args, children=children, **kwargs)

def wbr(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('wbr', *args, children=children, **kwargs)

def xmp(*args: TagChild, children: Optional[List[TagChild]] = None, **kwargs: AttrType) -> tag:
    return tag('xmp', *args, children=children, **kwargs)
