# Do not edit by hand; this file is generated by ./scripts/generate_tags.py
# fmt: off

from typing import Optional, List

from .core import Tag, TagChildArg, TagAttrArg

__all__ = (
    'p',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'a',
    'br',
    'div',
    'span',
    'pre',
    'code',
    'img',
    'strong',
    'em',
    'hr',
)


def a(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('a', *args, children=children, **kwargs)

def abbr(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('abbr', *args, children=children, **kwargs)

def acronym(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('acronym', *args, children=children, **kwargs)

def address(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('address', *args, children=children, **kwargs)

def animate(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('animate', *args, children=children, **kwargs)

def animateMotion(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('animateMotion', *args, children=children, **kwargs)

def animateTransform(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('animateTransform', *args, children=children, **kwargs)

def applet(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('applet', *args, children=children, **kwargs)

def area(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('area', *args, children=children, **kwargs)

def article(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('article', *args, children=children, **kwargs)

def aside(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('aside', *args, children=children, **kwargs)

def audio(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('audio', *args, children=children, **kwargs)

def b(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('b', *args, children=children, **kwargs)

def base(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('base', *args, children=children, **kwargs)

def basefont(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('basefont', *args, children=children, **kwargs)

def bdi(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('bdi', *args, children=children, **kwargs)

def bdo(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('bdo', *args, children=children, **kwargs)

def bgsound(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('bgsound', *args, children=children, **kwargs)

def big(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('big', *args, children=children, **kwargs)

def blink(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('blink', *args, children=children, **kwargs)

def blockquote(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('blockquote', *args, children=children, **kwargs)

def body(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('body', *args, children=children, **kwargs)

def br(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('br', *args, children=children, **kwargs)

def button(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('button', *args, children=children, **kwargs)

def canvas(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('canvas', *args, children=children, **kwargs)

def caption(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('caption', *args, children=children, **kwargs)

def center(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('center', *args, children=children, **kwargs)

def circle(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('circle', *args, children=children, **kwargs)

def cite(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('cite', *args, children=children, **kwargs)

def clipPath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('clipPath', *args, children=children, **kwargs)

def code(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('code', *args, children=children, **kwargs)

def col(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('col', *args, children=children, **kwargs)

def colgroup(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('colgroup', *args, children=children, **kwargs)

def command(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('command', *args, children=children, **kwargs)

def content(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('content', *args, children=children, **kwargs)

def data(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('data', *args, children=children, **kwargs)

def datalist(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('datalist', *args, children=children, **kwargs)

def dd(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('dd', *args, children=children, **kwargs)

def defs(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('defs', *args, children=children, **kwargs)

def desc(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('desc', *args, children=children, **kwargs)

def details(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('details', *args, children=children, **kwargs)

def dfn(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('dfn', *args, children=children, **kwargs)

def dialog(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('dialog', *args, children=children, **kwargs)

def dir(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('dir', *args, children=children, **kwargs)

def discard(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('discard', *args, children=children, **kwargs)

def div(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('div', *args, children=children, **kwargs)

def dl(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('dl', *args, children=children, **kwargs)

def dt(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('dt', *args, children=children, **kwargs)

def ellipse(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('ellipse', *args, children=children, **kwargs)

def em(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('em', *args, children=children, **kwargs)

def embed(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('embed', *args, children=children, **kwargs)

def eventsource(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('eventsource', *args, children=children, **kwargs)

def feBlend(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feBlend', *args, children=children, **kwargs)

def feColorMatrix(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feColorMatrix', *args, children=children, **kwargs)

def feComponentTransfer(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feComponentTransfer', *args, children=children, **kwargs)

def feComposite(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feComposite', *args, children=children, **kwargs)

def feConvolveMatrix(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feConvolveMatrix', *args, children=children, **kwargs)

def feDiffuseLighting(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feDiffuseLighting', *args, children=children, **kwargs)

def feDisplacementMap(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feDisplacementMap', *args, children=children, **kwargs)

def feDistantLight(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feDistantLight', *args, children=children, **kwargs)

def feDropShadow(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feDropShadow', *args, children=children, **kwargs)

def feFlood(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feFlood', *args, children=children, **kwargs)

def feFuncA(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feFuncA', *args, children=children, **kwargs)

def feFuncB(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feFuncB', *args, children=children, **kwargs)

def feFuncG(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feFuncG', *args, children=children, **kwargs)

def feFuncR(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feFuncR', *args, children=children, **kwargs)

def feGaussianBlur(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feGaussianBlur', *args, children=children, **kwargs)

def feImage(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feImage', *args, children=children, **kwargs)

def feMerge(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feMerge', *args, children=children, **kwargs)

def feMergeNode(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feMergeNode', *args, children=children, **kwargs)

def feMorphology(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feMorphology', *args, children=children, **kwargs)

def feOffset(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feOffset', *args, children=children, **kwargs)

def fePointLight(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('fePointLight', *args, children=children, **kwargs)

def feSpecularLighting(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feSpecularLighting', *args, children=children, **kwargs)

def feSpotLight(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feSpotLight', *args, children=children, **kwargs)

def feTile(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feTile', *args, children=children, **kwargs)

def feTurbulence(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('feTurbulence', *args, children=children, **kwargs)

def fieldset(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('fieldset', *args, children=children, **kwargs)

def figcaption(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('figcaption', *args, children=children, **kwargs)

def figure(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('figure', *args, children=children, **kwargs)

def filter(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('filter', *args, children=children, **kwargs)

def font(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('font', *args, children=children, **kwargs)

def footer(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('footer', *args, children=children, **kwargs)

def foreignObject(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('foreignObject', *args, children=children, **kwargs)

def form(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('form', *args, children=children, **kwargs)

def frame(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('frame', *args, children=children, **kwargs)

def frameset(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('frameset', *args, children=children, **kwargs)

def g(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('g', *args, children=children, **kwargs)

def h1(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('h1', *args, children=children, **kwargs)

def h2(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('h2', *args, children=children, **kwargs)

def h3(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('h3', *args, children=children, **kwargs)

def h4(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('h4', *args, children=children, **kwargs)

def h5(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('h5', *args, children=children, **kwargs)

def h6(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('h6', *args, children=children, **kwargs)

def hatch(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('hatch', *args, children=children, **kwargs)

def hatchpath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('hatchpath', *args, children=children, **kwargs)

def head(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('head', *args, children=children, **kwargs)

def header(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('header', *args, children=children, **kwargs)

def hgroup(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('hgroup', *args, children=children, **kwargs)

def hr(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('hr', *args, children=children, **kwargs)

def html(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('html', *args, children=children, **kwargs)

def i(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('i', *args, children=children, **kwargs)

def iframe(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('iframe', *args, children=children, **kwargs)

def image(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('image', *args, children=children, **kwargs)

def img(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('img', *args, children=children, **kwargs)

def input(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('input', *args, children=children, **kwargs)

def ins(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('ins', *args, children=children, **kwargs)

def kbd(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('kbd', *args, children=children, **kwargs)

def keygen(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('keygen', *args, children=children, **kwargs)

def label(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('label', *args, children=children, **kwargs)

def legend(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('legend', *args, children=children, **kwargs)

def li(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('li', *args, children=children, **kwargs)

def line(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('line', *args, children=children, **kwargs)

def linearGradient(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('linearGradient', *args, children=children, **kwargs)

def link(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('link', *args, children=children, **kwargs)

def main(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('main', *args, children=children, **kwargs)

def map(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('map', *args, children=children, **kwargs)

def mark(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('mark', *args, children=children, **kwargs)

def marker(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('marker', *args, children=children, **kwargs)

def marquee(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('marquee', *args, children=children, **kwargs)

def mask(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('mask', *args, children=children, **kwargs)

def menu(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('menu', *args, children=children, **kwargs)

def menuitem(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('menuitem', *args, children=children, **kwargs)

def mesh(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('mesh', *args, children=children, **kwargs)

def meshgradient(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('meshgradient', *args, children=children, **kwargs)

def meshpatch(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('meshpatch', *args, children=children, **kwargs)

def meshrow(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('meshrow', *args, children=children, **kwargs)

def meta(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('meta', *args, children=children, **kwargs)

def metadata(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('metadata', *args, children=children, **kwargs)

def meter(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('meter', *args, children=children, **kwargs)

def mpath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('mpath', *args, children=children, **kwargs)

def nav(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('nav', *args, children=children, **kwargs)

def nobr(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('nobr', *args, children=children, **kwargs)

def noembed(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('noembed', *args, children=children, **kwargs)

def noframes(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('noframes', *args, children=children, **kwargs)

def noscript(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('noscript', *args, children=children, **kwargs)

def object(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('object', *args, children=children, **kwargs)

def ol(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('ol', *args, children=children, **kwargs)

def optgroup(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('optgroup', *args, children=children, **kwargs)

def option(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('option', *args, children=children, **kwargs)

def output(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('output', *args, children=children, **kwargs)

def p(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('p', *args, children=children, **kwargs)

def param(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('param', *args, children=children, **kwargs)

def path(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('path', *args, children=children, **kwargs)

def pattern(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('pattern', *args, children=children, **kwargs)

def picture(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('picture', *args, children=children, **kwargs)

def plaintext(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('plaintext', *args, children=children, **kwargs)

def polygon(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('polygon', *args, children=children, **kwargs)

def polyline(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('polyline', *args, children=children, **kwargs)

def portal(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('portal', *args, children=children, **kwargs)

def pre(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('pre', *args, children=children, **kwargs)

def progress(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('progress', *args, children=children, **kwargs)

def q(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('q', *args, children=children, **kwargs)

def radialGradient(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('radialGradient', *args, children=children, **kwargs)

def rb(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('rb', *args, children=children, **kwargs)

def rect(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('rect', *args, children=children, **kwargs)

def rp(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('rp', *args, children=children, **kwargs)

def rt(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('rt', *args, children=children, **kwargs)

def rtc(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('rtc', *args, children=children, **kwargs)

def ruby(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('ruby', *args, children=children, **kwargs)

def s(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('s', *args, children=children, **kwargs)

def samp(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('samp', *args, children=children, **kwargs)

def script(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('script', *args, children=children, **kwargs)

def section(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('section', *args, children=children, **kwargs)

def select(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('select', *args, children=children, **kwargs)

def set(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('set', *args, children=children, **kwargs)

def shadow(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('shadow', *args, children=children, **kwargs)

def slot(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('slot', *args, children=children, **kwargs)

def small(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('small', *args, children=children, **kwargs)

def solidcolor(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('solidcolor', *args, children=children, **kwargs)

def source(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('source', *args, children=children, **kwargs)

def spacer(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('spacer', *args, children=children, **kwargs)

def span(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('span', *args, children=children, **kwargs)

def stop(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('stop', *args, children=children, **kwargs)

def strike(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('strike', *args, children=children, **kwargs)

def strong(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('strong', *args, children=children, **kwargs)

def style(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('style', *args, children=children, **kwargs)

def sub(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('sub', *args, children=children, **kwargs)

def summary(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('summary', *args, children=children, **kwargs)

def sup(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('sup', *args, children=children, **kwargs)

def svg(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('svg', *args, children=children, **kwargs)

def switch(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('switch', *args, children=children, **kwargs)

def symbol(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('symbol', *args, children=children, **kwargs)

def table(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('table', *args, children=children, **kwargs)

def tbody(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('tbody', *args, children=children, **kwargs)

def td(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('td', *args, children=children, **kwargs)

def template(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('template', *args, children=children, **kwargs)

def text(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('text', *args, children=children, **kwargs)

def textarea(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('textarea', *args, children=children, **kwargs)

def textPath(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('textPath', *args, children=children, **kwargs)

def tfoot(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('tfoot', *args, children=children, **kwargs)

def th(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('th', *args, children=children, **kwargs)

def thead(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('thead', *args, children=children, **kwargs)

def time(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('time', *args, children=children, **kwargs)

def title(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('title', *args, children=children, **kwargs)

def tr(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('tr', *args, children=children, **kwargs)

def track(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('track', *args, children=children, **kwargs)

def tspan(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('tspan', *args, children=children, **kwargs)

def tt(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('tt', *args, children=children, **kwargs)

def u(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('u', *args, children=children, **kwargs)

def ul(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('ul', *args, children=children, **kwargs)

def unknown(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('unknown', *args, children=children, **kwargs)

def use(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('use', *args, children=children, **kwargs)

def var(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('var', *args, children=children, **kwargs)

def video(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('video', *args, children=children, **kwargs)

def view(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('view', *args, children=children, **kwargs)

def wbr(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('wbr', *args, children=children, **kwargs)

def xmp(*args: TagChildArg, children: Optional[List[TagChildArg]] = None, **kwargs: TagAttrArg) -> Tag:
    return Tag('xmp', *args, children=children, **kwargs)
