name: Bleeding Edge Shiny

on:
  push:
    branches: "shiny-**"
  pull_request:

jobs:
  htmltools-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          repository: posit-dev/py-shiny
          fetch-depth: 0 # Required for shiny version
      - name: Setup py-shiny@main
        id: install
        uses: posit-dev/py-shiny/.github/py-shiny/setup
        with:
          python-version: "3.12"

      - uses: actions/checkout@v4
        with:
          path: htmltools

      - name: Install dev py-htmltools htmltools dependencies
        run: |
          cd htmltools
          pip install -e ".[dev,test]"
          make install

      - name: Check py-shiny@main w/ dev py-htmltools
        run: |
          # Run test before check, so that linting is performed last
          make test check
